apiVersion: apps/v1
kind: Deployment
metadata:
  name: packet-handler
  labels:
    run: packet-handler
spec:
  replicas: 2
  selector:
    matchLabels:
      run: packet-handler
  template:
    metadata:
      labels:
        run: packet-handler
    spec:
      containers:
        - name: packet-handler
          image: tothalex97/udp
          ports:
            - name: udp
              containerPort: 80
              protocol: UDP
            - name: tcp
              containerPort: 80
              protocol: TCP
            - containerPort: 9000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 20
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
